# Questo file configura il comportamento di Netlify per il tuo sito.

# Specifica dove si trovano le tue Netlify Functions.
[functions]
  directory = "netlify/functions/"

# Definisce una funzione programmata (scheduled function).
# Usa la sintassi "cron job" per definire l'intervallo.
# "0 * * * *" significa: "Esegui allo scoccare di ogni ora".
[functions."update-data"]
  schedule = "0 * * * *"
