# Questo file configura il comportamento di Netlify per il tuo sito.

# Specifica dove si trovano le tue Netlify Functions.
[functions]
  directory = "netlify/functions/"

# Definisce una funzione programmata (scheduled function).
# Usa la sintassi "cron job" per definire l'intervallo.
# "0 */4 * * *" significa: "Esegui allo scoccare dell'ora, ogni 4 ore".
# (es. a mezzanotte, alle 4:00, alle 8:00, ecc.)
[functions."update-data"]
  schedule = "0 */4 * * *"
